#!/bin/sh
#
# Usage:
#
#    sh install.sh
#
# Environment variables: VERBOSE, CP, LN, MKDIR, RM, DIRNAME, XARGS.
#
#    env VERBOSE=1 sh install.sh
#
# DO NOT EDIT THIS FILE
# 
# This file is generated by rcm(7) as:
#
#   rcup -B 0 -g
#
# To update it, re-run the above command.
#
: ${VERBOSE:=0}
: ${CP:=/bin/cp}
: ${LN:=/bin/ln}
: ${MKDIR:=/bin/mkdir}
: ${RM:=/bin/rm}
: ${DIRNAME:=/usr/bin/dirname}
: ${XARGS:=/usr/bin/xargs}
verbose() {
  if [ "$VERBOSE" -gt 0 ]; then
    echo "$@"
  fi
}
handle_file_cp() {
  if [ -e "$2" ]; then
    printf "%s " "overwrite $2? [yN]"
    read overwrite
    case "$overwrite" in
      y)
        $RM -rf "$2"
        ;;
      *)
        echo "skipping $2"
        return
        ;;
    esac
  fi
  verbose "'$1' -> '$2'"
  $DIRNAME "$2" | $XARGS $MKDIR -p
  $CP -R "$1" "$2"
}
handle_file_ln() {
  if [ -e "$2" ]; then
    printf "%s " "overwrite $2? [yN]"
    read overwrite
    case "$overwrite" in
      y)
        $RM -rf "$2"
        ;;
      *)
        echo "skipping $2"
        return
        ;;
    esac
  fi
  verbose "'$1' -> '$2'"
  $DIRNAME "$2" | $XARGS $MKDIR -p
  $LN -sf "$1" "$2"
}
handle_file_ln "/home/chris/.dotfiles/agignore" "/home/chris/.agignore"
handle_file_ln "/home/chris/.dotfiles/config/fontconfig/conf.d/10-powerline-symbols.conf" "/home/chris/.config/fontconfig/conf.d/10-powerline-symbols.conf"
handle_file_ln "/home/chris/.dotfiles/config/i3/config" "/home/chris/.config/i3/config"
handle_file_ln "/home/chris/.dotfiles/config/systemd/user/app@.service" "/home/chris/.config/systemd/user/app@.service"
handle_file_ln "/home/chris/.dotfiles/config/systemd/user/dropbox.service" "/home/chris/.config/systemd/user/dropbox.service"
handle_file_ln "/home/chris/.dotfiles/config/systemd/user/mpd.service" "/home/chris/.config/systemd/user/mpd.service"
handle_file_ln "/home/chris/.dotfiles/config/systemd/user/mystuff.target" "/home/chris/.config/systemd/user/mystuff.target"
handle_file_ln "/home/chris/.dotfiles/config/systemd/user/mystuff.target.wants/dropbox.service" "/home/chris/.config/systemd/user/mystuff.target.wants/dropbox.service"
handle_file_ln "/home/chris/.dotfiles/config/systemd/user/mystuff.target.wants/mpd.service" "/home/chris/.config/systemd/user/mystuff.target.wants/mpd.service"
handle_file_ln "/home/chris/.dotfiles/config/systemd/user/mystuff.target.wants/tmp.service" "/home/chris/.config/systemd/user/mystuff.target.wants/tmp.service"
handle_file_ln "/home/chris/.dotfiles/config/systemd/user/mystuff.target.wants/xautolock.service" "/home/chris/.config/systemd/user/mystuff.target.wants/xautolock.service"
handle_file_ln "/home/chris/.dotfiles/config/systemd/user/tmp.service" "/home/chris/.config/systemd/user/tmp.service"
handle_file_ln "/home/chris/.dotfiles/config/systemd/user/xautolock.service" "/home/chris/.config/systemd/user/xautolock.service"
handle_file_ln "/home/chris/.dotfiles/config/xfce4/terminal/terminalrc" "/home/chris/.config/xfce4/terminal/terminalrc"
handle_file_ln "/home/chris/.dotfiles/conkyrc" "/home/chris/.conkyrc"
handle_file_ln "/home/chris/.dotfiles/fonts/PowerlineSymbols.otf" "/home/chris/.fonts/PowerlineSymbols.otf"
handle_file_ln "/home/chris/.dotfiles/gitconfig" "/home/chris/.gitconfig"
handle_file_ln "/home/chris/.dotfiles/gitignore" "/home/chris/.gitignore"
handle_file_ln "/home/chris/.dotfiles/gitignore_global" "/home/chris/.gitignore_global"
handle_file_ln "/home/chris/.dotfiles/i3/config" "/home/chris/.i3/config"
handle_file_ln "/home/chris/.dotfiles/install.sh" "/home/chris/.install.sh"
handle_file_ln "/home/chris/.dotfiles/kde4/share/apps/konsole/Shell.profile" "/home/chris/.kde4/share/apps/konsole/Shell.profile"
handle_file_ln "/home/chris/.dotfiles/kde4/share/config/konsolerc" "/home/chris/.kde4/share/config/konsolerc"
handle_file_ln "/home/chris/.dotfiles/local/bin/git-wip" "/home/chris/.local/bin/git-wip"
handle_file_ln "/home/chris/.dotfiles/local/bin/i3bar-conky" "/home/chris/.local/bin/i3bar-conky"
handle_file_ln "/home/chris/.dotfiles/local/bin/i3-name" "/home/chris/.local/bin/i3-name"
handle_file_ln "/home/chris/.dotfiles/lock.png" "/home/chris/.lock.png"
handle_file_ln "/home/chris/.dotfiles/makepkg.conf" "/home/chris/.makepkg.conf"
handle_file_ln "/home/chris/.dotfiles/provisioning/pillars/pkgs.sls" "/home/chris/.provisioning/pillars/pkgs.sls"
handle_file_ln "/home/chris/.dotfiles/provisioning/pillars/top.sls" "/home/chris/.provisioning/pillars/top.sls"
handle_file_ln "/home/chris/.dotfiles/provisioning/provision.sh" "/home/chris/.provisioning/provision.sh"
handle_file_ln "/home/chris/.dotfiles/provisioning/states/base.sls" "/home/chris/.provisioning/states/base.sls"
handle_file_ln "/home/chris/.dotfiles/provisioning/states/desktop.sls" "/home/chris/.provisioning/states/desktop.sls"
handle_file_ln "/home/chris/.dotfiles/provisioning/states/laptop.sls" "/home/chris/.provisioning/states/laptop.sls"
handle_file_ln "/home/chris/.dotfiles/provisioning/states/top.sls" "/home/chris/.provisioning/states/top.sls"
handle_file_ln "/home/chris/.dotfiles/provisioning/states/vim.sls" "/home/chris/.provisioning/states/vim.sls"
handle_file_ln "/home/chris/.dotfiles/rcm-git-v1.2.3.r12.gdf29698-1-any.pkg.tar.gz" "/home/chris/.rcm-git-v1.2.3.r12.gdf29698-1-any.pkg.tar.gz"
handle_file_ln "/home/chris/.dotfiles/README.md" "/home/chris/.README.md"
handle_file_ln "/home/chris/.dotfiles/tmux.conf" "/home/chris/.tmux.conf"
handle_file_ln "/home/chris/.dotfiles/vim/01-bundles.vim" "/home/chris/.vim/01-bundles.vim"
handle_file_ln "/home/chris/.dotfiles/vim/02-display.vim" "/home/chris/.vim/02-display.vim"
handle_file_ln "/home/chris/.dotfiles/vim/03-input.vim" "/home/chris/.vim/03-input.vim"
handle_file_ln "/home/chris/.dotfiles/vim/04-commands.vim" "/home/chris/.vim/04-commands.vim"
handle_file_ln "/home/chris/.dotfiles/vim/06-autocommands.vim" "/home/chris/.vim/06-autocommands.vim"
handle_file_ln "/home/chris/.dotfiles/vim/49-file-finder.vim" "/home/chris/.vim/49-file-finder.vim"
handle_file_ln "/home/chris/.dotfiles/vim/50-plugins-CommandT.vim" "/home/chris/.vim/50-plugins-CommandT.vim"
handle_file_ln "/home/chris/.dotfiles/vim/50-plugins-goyo.vim" "/home/chris/.vim/50-plugins-goyo.vim"
handle_file_ln "/home/chris/.dotfiles/vim/50-plugins-lightline.vim" "/home/chris/.vim/50-plugins-lightline.vim"
handle_file_ln "/home/chris/.dotfiles/vim/50-plugins-move.vim" "/home/chris/.vim/50-plugins-move.vim"
handle_file_ln "/home/chris/.dotfiles/vim/50-plugins-python-mode.vim" "/home/chris/.vim/50-plugins-python-mode.vim"
handle_file_ln "/home/chris/.dotfiles/vim/50-plugins-Syntastic,vim" "/home/chris/.vim/50-plugins-Syntastic,vim"
handle_file_ln "/home/chris/.dotfiles/vim/50-plugins-undotree.vim" "/home/chris/.vim/50-plugins-undotree.vim"
handle_file_ln "/home/chris/.dotfiles/vim/50-plugins-unite.vim" "/home/chris/.vim/50-plugins-unite.vim"
handle_file_ln "/home/chris/.dotfiles/vim/50-plugins-vim-git.vim" "/home/chris/.vim/50-plugins-vim-git.vim"
handle_file_ln "/home/chris/.dotfiles/vim/50-plugins-YouCompleteMe.vim" "/home/chris/.vim/50-plugins-YouCompleteMe.vim"
handle_file_ln "/home/chris/.dotfiles/vim/60-autorestart-on-save.vim" "/home/chris/.vim/60-autorestart-on-save.vim"
handle_file_ln "/home/chris/.dotfiles/vim/70-filetype-rst.vim" "/home/chris/.vim/70-filetype-rst.vim"
handle_file_ln "/home/chris/.dotfiles/vim/70-filetype-thrift.vim" "/home/chris/.vim/70-filetype-thrift.vim"
handle_file_ln "/home/chris/.dotfiles/vim/create_minimal.sh" "/home/chris/.vim/create_minimal.sh"
handle_file_ln "/home/chris/.dotfiles/vim/minimal_vimrc" "/home/chris/.vim/minimal_vimrc"
handle_file_ln "/home/chris/.dotfiles/vim/README.rst" "/home/chris/.vim/README.rst"
handle_file_ln "/home/chris/.dotfiles/vim/vimrc" "/home/chris/.vim/vimrc"
handle_file_ln "/home/chris/.dotfiles/workspaces/vmmp_1server" "/home/chris/.workspaces/vmmp_1server"
handle_file_ln "/home/chris/.dotfiles/workspaces/vmmp_1server.sh" "/home/chris/.workspaces/vmmp_1server.sh"
handle_file_ln "/home/chris/.dotfiles/workspaces/vmmp_2server" "/home/chris/.workspaces/vmmp_2server"
handle_file_ln "/home/chris/.dotfiles/workspaces/vmmp_2server.sh" "/home/chris/.workspaces/vmmp_2server.sh"
handle_file_ln "/home/chris/.dotfiles/workspaces/vmmp_3server" "/home/chris/.workspaces/vmmp_3server"
handle_file_ln "/home/chris/.dotfiles/workspaces/vmmp_3server.sh" "/home/chris/.workspaces/vmmp_3server.sh"
handle_file_ln "/home/chris/.dotfiles/workspaces/vmmp_4server" "/home/chris/.workspaces/vmmp_4server"
handle_file_ln "/home/chris/.dotfiles/workspaces/vmmp_4server.sh" "/home/chris/.workspaces/vmmp_4server.sh"
handle_file_ln "/home/chris/.dotfiles/workspaces/vmmp_stacked" "/home/chris/.workspaces/vmmp_stacked"
handle_file_ln "/home/chris/.dotfiles/workspaces/vmmp_stacked.sh" "/home/chris/.workspaces/vmmp_stacked.sh"
handle_file_ln "/home/chris/.dotfiles/yaourtrc" "/home/chris/.yaourtrc"
handle_file_ln "/home/chris/.dotfiles/zsh/01-antigen.zsh" "/home/chris/.zsh/01-antigen.zsh"
handle_file_ln "/home/chris/.dotfiles/zsh/02-zsh-main.zsh" "/home/chris/.zsh/02-zsh-main.zsh"
handle_file_ln "/home/chris/.dotfiles/zsh/10-expand-or-complete-with-dots.zsh" "/home/chris/.zsh/10-expand-or-complete-with-dots.zsh"
handle_file_ln "/home/chris/.dotfiles/zsh/10-history.zsh" "/home/chris/.zsh/10-history.zsh"
handle_file_ln "/home/chris/.dotfiles/zsh/10-keybindings.zsh" "/home/chris/.zsh/10-keybindings.zsh"
handle_file_ln "/home/chris/.dotfiles/zsh/10-ssh-keys.zsh" "/home/chris/.zsh/10-ssh-keys.zsh"
handle_file_ln "/home/chris/.dotfiles/zsh/10-virtualenvwrapper.zsh" "/home/chris/.zsh/10-virtualenvwrapper.zsh"
handle_file_ln "/home/chris/.dotfiles/zsh/10-virtualenv.zsh" "/home/chris/.zsh/10-virtualenv.zsh"
handle_file_ln "/home/chris/.dotfiles/zsh/10-windowtitle.zsh" "/home/chris/.zsh/10-windowtitle.zsh"
handle_file_ln "/home/chris/.dotfiles/zsh/20-aws.zsh" "/home/chris/.zsh/20-aws.zsh"
handle_file_ln "/home/chris/.dotfiles/zsh/20-git-extras.zsh" "/home/chris/.zsh/20-git-extras.zsh"
handle_file_ln "/home/chris/.dotfiles/zsh/20-history-substring-search.zsh" "/home/chris/.zsh/20-history-substring-search.zsh"
handle_file_ln "/home/chris/.dotfiles/zsh/20-marks.zsh" "/home/chris/.zsh/20-marks.zsh"
handle_file_ln "/home/chris/.dotfiles/zsh/30-aliases.zsh" "/home/chris/.zsh/30-aliases.zsh"
handle_file_ln "/home/chris/.dotfiles/zsh/40-linux-conf.zsh" "/home/chris/.zsh/40-linux-conf.zsh"
handle_file_ln "/home/chris/.dotfiles/zsh/40-osx-conf.zsh" "/home/chris/.zsh/40-osx-conf.zsh"
handle_file_ln "/home/chris/.dotfiles/zsh/99-theme.zsh" "/home/chris/.zsh/99-theme.zsh"
handle_file_ln "/home/chris/.dotfiles/zsh/99-zsh-local.zsh" "/home/chris/.zsh/99-zsh-local.zsh"
handle_file_ln "/home/chris/.dotfiles/zshrc" "/home/chris/.zshrc"
