" Python mode settings.
let g:pymode_lint = 0
let g:pymode_run = 0
let g:pymode_folding = 0
nmap gd :call RopeGotoDefinition()<CR>
let g:pymode_breakpoint_key = '<C-c><Leader>b'
let g:pymode_doc = 0
let g:pymode_rope = 0
let g:pymode_breakpoint = 0
let g:pymode_options = 0
